name: Enviar resumen semanal del ECDC

on:
  workflow_dispatch:          # puedes lanzarlo a mano
  schedule:
    - cron: "0 8 * * 1"       # lunes 08:00 UTC

jobs:
  ecdc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Reset state (forzar nueva búsqueda)
        run: rm -f .agent_state.json
        
      - name: Download NLTK data
        run: |
          python -c "
          import nltk
          nltk.download('punkt', download_dir='$HOME/nltk_data')
          nltk.download('stopwords', download_dir='$HOME/nltk_data')
          print('NLTK data descargado correctamente')
          "

     - name: Test URLs manualmente
      run: |
        echo "=== 🔍 TEST MANUAL DE URLs ==="
        echo "Probando formato 2024:"
        curl -s -I "https://www.ecdc.europa.eu/sites/default/files/documents/communicable-disease-threats-report-2024-w35.pdf" | head -3
        echo ""
        curl -s -I "https://www.ecdc.europa.eu/sites/default/files/documents/communicable-disease-threats-report-2024-w34.pdf" | head -3
        echo ""
        echo "Probando formato antiguo:"
        curl -s -I "https://www.ecdc.europa.eu/sites/default/files/documents/communicable-disease-threats-report-week-35-2024.pdf" | head -3
        echo "=== FIN TEST ==="

- name: Run agent (DEBUG mode)
  env:
    LOG_LEVEL: DEBUG
    SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
    SMTP_PORT: ${{ secrets.SMTP_PORT }}
    SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
    RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  run: python weekly_agent.py
